blog/urls.py
from django.urls import path
from django.contrib.sitemaps.views import sitemap
from . import views
from .feeds import LatestEntriesFeed
from .sitemap import (
    PostSitemap, TagSitemap,
    CategorySitemap, StaticSitemap
)

app_name = 'blog'

sitemaps = {
    'post': PostSitemap,
    'category': CategorySitemap,
    'tag': TagSitemap,
    'static': StaticSitemap,
}


urlpatterns = [
    path('', views.PostIndexView.as_view(), name='index'),

    path('ping/', views.ping, name='ping'),

    path('alltag/', views.TagListView.as_view(), name='tag_list'),

    path('detail/<int:pk>/', views.PostDetailView.as_view(), name='detail'),

    path('category/<str:category>/', views.CategoryView.as_view(), name='category'),

    path('tag/<str:tag>/', views.TagView.as_view(), name='tag'),

    path('comment/<int:pk>/', views.CommentCreateView.as_view(), name='comment'),
    path('recomment/<int:pk>/', views.ReCommentCreateView.as_view(), name='recomment'),
    path('file_download/<int:pk>/', views.file_download, name='file_download'),


    path('private/', views.PostPrivateIndexView.as_view(), name='private'),

    path('latest/feed/', LatestEntriesFeed(), name='feed'),
    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
]

blog/models.py
import os
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.contrib.sites.models import Site
from django.db import models
from django.utils import timezone


# サイト詳細情報のテーマカラーの選択肢
SITE_COLORS = (
    ('primary', '青色'),
    ('secondary', '灰色'),
    ('success', '緑色'),
    ('info', '水色'),
    ('warning', '黄色'),
    ('danger', '赤'),
    ('dark', '黒'),
)

DEFAULT_HEADER_TEXT = """\
このブログはDjangoとBootstrap4で作成されました
[filter url]https://github.com/naritotzawa/django-torina-blog<split>Githubのソースコード[end]\
"""


class Category(models.Model):
    """カテゴリー"""
    name = models.CharField('カテゴリ名', max_length=255)

    def __str__(self):
        """str."""
        return self.name


class Tag(models.Model):
    """タグ"""
    name = models.CharField('タグ名', max_length=255)

    def __str__(self):
        """str."""
        return self.name


class Post(models.Model):
    """記事"""
    title = models.CharField('タイトル', max_length=255)
    text = models.TextField('本文')
    category = models.ForeignKey(
        Category, verbose_name='カテゴリ', on_delete=models.PROTECT)
    tag = models.ManyToManyField(Tag, blank=True, verbose_name='タグ')
    thumnail = models.ImageField(
        'サムネイル', upload_to='post_thumbnail/%Y/%m/%d/', blank=True, null=True)
    is_publick = models.BooleanField('公開可能か?', default=True)
    friend_posts = models.ManyToManyField(
        'self', verbose_name='関連記事', blank=True)
    description = models.TextField('記事の説明', blank=True)
    files = GenericRelation('File')
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.title

    def get_description(self):
        if self.description:
            return self.description
        else:
            description = 'カテゴリ:{0} タグ:{1}'
            category = self.category
            tags = ' '.join(tag.name for tag in self.tag.all())
            description = description.format(category, tags)
            return description

    def get_next(self):
        """次の記事を取得する(日付)

        パフォーマンス的に、無駄が多い処理ですが、APIとして一応残しておきます。
        """
        next_post = Post.objects.filter(
            is_publick=True, created_at__gt=self.created_at
        ).order_by('-created_at')
        if next_post:
            return next_post.last()
        return None

    def get_prev(self):
        """前の記事を取得する(日付)

        パフォーマンス的に、無駄が多い処理ですが、APIとして一応残しておきます。
        """
        prev_post = Post.objects.filter(
            is_publick=True, created_at__lt=self.created_at
        ).order_by('-created_at')
        if prev_post:
            return prev_post.first()
        return None


class Comment(models.Model):
    """コメント"""
    name = models.CharField('名前', max_length=255, default='名無し')
    text = models.TextField('コメント')
    icon = models.ImageField(
        'サムネイル', upload_to='comment_thumbnail/%Y/%m/%d/', blank=True, null=True)
    target = models.ForeignKey(
        Post, on_delete=models.CASCADE, verbose_name='対象記事')
    files = GenericRelation('File')
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.text[:10]

    def get_filename(self):
        """ファイル名を取得する"""
        return os.path.basename(self.file.url)


class ReComment(models.Model):
    """返信コメント"""
    name = models.CharField('名前', max_length=255, default='名無し')
    text = models.TextField('コメント')
    icon = models.ImageField(
        'サムネイル', upload_to='recomment_thumbnail/%Y/%m/%d//', blank=True, null=True)
    target = models.ForeignKey(
        Comment, on_delete=models.CASCADE, verbose_name='対象コメント')
    files = GenericRelation('File')
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.text[:10]

    def get_filename(self):
        """ファイル名を取得する"""
        return os.path.basename(self.file.url)


class Link(models.Model):
    """リンク"""
    name = models.CharField('リンク名', max_length=255)
    adrs = models.CharField('アドレス', max_length=255)

    def __str__(self):
        return self.name


class Analytics(models.Model):
    """アナリティクスの情報"""
    name = models.CharField('アナリティクス', max_length=255, blank=True)
    html = models.TextField('アナリティクスHTML', blank=True)

    def __str__(self):
        return self.name


class Ads(models.Model):
    """広告関連"""
    name = models.CharField('広告名', max_length=255, blank=True)
    html = models.TextField('広告HTML', blank=True)

    def __str__(self):
        return self.name


class SiteDetail(models.Model):
    """サイトの詳細情報"""
    site = models.OneToOneField(Site, verbose_name='Site', on_delete=models.PROTECT)
    title = models.CharField('タイトル', max_length=255, default='サンプルのタイトル')
    header_text = models.TextField('ヘッダーのテキスト', max_length=255, default=DEFAULT_HEADER_TEXT)
    description = models.TextField('サイトの説明', max_length=255, default='サンプルの説明')
    author = models.CharField('管理者', max_length=255, default='サンプルの管理者')
    author_mail = models.EmailField('管理者アドレス', max_length=255, default='your_mail@gmail.com')
    color = models.CharField('サイトテーマ色', choices=SITE_COLORS, default='primary', max_length=30)

    def __str__(self):
        return self.author


class PopularPost(models.Model):
    """人気記事"""
    title = models.CharField('タイトル', max_length=255)
    url = models.CharField('URL', max_length=255)
    page_view = models.IntegerField('ページビュー数')

    def __str__(self):
        return '{0} - {1} - {2}'.format(
            self.url, self.title, self.page_view)


class Image(models.Model):
    """記事に紐づく画像ファイル"""
    title = models.CharField('タイトル', max_length=255, blank=True)
    post = models.ForeignKey(
        Post, verbose_name='記事', on_delete=models.PROTECT,
    )
    src = models.ImageField('画像', upload_to='images/%Y/%m/%d/', help_text='送信後、一度保存してください。')
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return '間接リンク:[filter imgpk]{0}[end] 直接リンク:[filter img]{1}[end]'.format(self.pk, self.src.url)


class File(models.Model):
    """記事やコメントに紐づく添付ファイル"""
    title = models.CharField('タイトル', max_length=255, blank=True)
    src = models.FileField('添付ファイル', upload_to='files/%Y/%m/%d/')
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return 'モデル:{} pk:{} url:{}'.format(self.content_type, self.object_id, self.src.url)

    def get_filename(self):
        """ファイル名を取得する"""
        return os.path.basename(self.src.url)

blog/templates/blog/widgets/detail_card.html
{% load blogfilter %}
{% load static %}
<style>
    pre.prettyprint {
      white-space: pre;
    }
    .prettyprint ol.linenums > li {
      list-style-type: decimal; 
    }
</style>
<div class="card">
  <div class="card-header bg-{{ mysite.color }}">
    <h1 class="card-title text-white">{{ post.title }}</h1>
  </div>
  
  <div class="card-body">
      <span class="badge badge-{{ mysite.color }} badge-pill">{% by_the_time post.created_at %}</span>
      <span class="badge badge-{{ mysite.color }} badge-pill">{{ post.created_at }}</span>
      <br>
  
      <span class="badge badge-{{ mysite.color }}">
        <a class="text-white" href="{% url 'blog:category' post.category.name %}">{{ post.category.name }}</a>
      </span>
      <br>
  
      {% for tag in post.tag.all %}
        <span class="badge badge-{{ mysite.color }}">
          <a class="text-white" href="{% url 'blog:tag' tag.name %}">{{ tag.name }}</a>
        </span>
      {% endfor %}
      <hr>
  
      {% if user.is_authenticated %}
        <a href="{% url 'admin:blog_post_change' post.pk %}">管理画面へ</a>
        <hr>
      {% endif %}
    
    {{ post.text | linebreaksbr | blog }}
  </div>
  
  <div class="card-footer">
    <p>添付ファイル</p>
    {% for file in post.files.all %}
      <a href="{% url 'blog:file_download' file.pk %}">{{ file.title }} - {{ file.get_filename }}</a><br>
    {% endfor %}
  
    <p>関連記事</p>
    {% for post in post.friend_posts.all %}
      {% if post.is_publick %}
          <p><a href="{% url 'blog:detail' post.pk %}">{{ post.title }}</a></p>
      {% endif %}
    {% endfor %}    
  
  </div>
</div>
<script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js?skin=desert"></script>

blog/templates/blog/widgets/detail_comment.html
{% load blogfilter %}
{% load static %}
<div class="row mt-3">
  <div class="col-md-2 d-none d-md-block">
    {% if comment.icon %}
      <img class="img-fluid lazy" data-original="{{ comment.icon.url }}">
    {% else %}
      <img class="img-fluid lazy" data-original="{% static 'blog/img/noimage.png' %}">
    {% endif %}
  </div>
  <div class="col-md-10">
      <h5>
        {{ comment.name }}
        <span class="badge badge-{{ mysite.color }} badge-pill">{% by_the_time comment.created_at %}</span>
        <span class="badge badge-{{ mysite.color }} badge-pill">{{ comment.created_at }}</span>
        <a href="{% url 'blog:recomment' comment.pk %}">返信する</a>
      </h5>
      {% for file in comment.files.all %}
        <a href="{% url 'blog:file_download' file.pk %}">添付ファイルダウンロード({{ file.get_filename }})</a><br>
      {% endfor %}
      {{ comment.text | linebreaksbr }}
      <!-- 返信コメント -->
      {% for recomment in comment.recomment_set.all %}
        <div class="row mt-3">
          <div class="col-md-2 d-none d-md-block">
            {% if recomment.icon %}
              <img class="img-fluid lazy" data-original="{{ recomment.icon.url }}">
            {% else %}
              <img class="img-fluid lazy" data-original="{% static 'blog/img/noimage.png' %}">
            {% endif %}
          </div>
          <div class="col-md-10">
              <h5>
                {{ recomment.name }}
                <span class="badge badge-{{ mysite.color }} badge-pill">{% by_the_time recomment.created_at %}</span>
                <span class="badge badge-{{ mysite.color }} badge-pill">{{ recomment.created_at }}</span>
              </h5>
              {% for file in recomment.files.all %}
                <a href="{% url 'blog:file_download' file.pk %}">添付ファイルダウンロード({{ file.get_filename }})</a><br>
              {% endfor %}
              {{ recomment.text | linebreaksbr }}
        
          </div>
        </div>
      {% endfor %}
      <!-- 返信コメントおわり -->
  </div>
</div>

blog/templates/blog/widgets/footer.html
<footer class="text-center bg-{{ mysite.color }}">
  <div class="container">
    <p class="text-white">Copyright {{ mysite.author }} All Rights Reserved.</p>
    <p><a href="mailto:{{ mysite.author_mail }}" rel="nofollow">{{ mysite.author_mail }}</a></p>
  </div>
</footer>

blog/templates/blog/widgets/header.html
{% load blogfilter %}
<header class="jumbotron">
  <div class="container">
    <h1>{{ mysite.title }}</h1>
    {{ mysite.header_text | linebreaksbr | blog }}
  </div>
</header>

blog/templates/blog/widgets/list_card.html
{% load blogfilter %}
{% load static %}

<div class="mb-5 card">

  <div class="card-header bg-{{ mysite.color }}">
    <h1 class="card-title text-white">{{ post.title }}</h1>
  </div><!-- card-header終了 -->
  
  <div class="card-body row">
    <!-- card-bodyの左側 -->
    <div class="col-xs-12 col-sm-6 text-center">
      {% if post.thumnail %}
        <a href="{{ post.thumnail.url }}" target="_blank" rel="nofollow"><img class="img-fluid lazy" data-original="{{ post.thumnail.url }}" alt="{{ post.title }}"></a>
      {% else %}
        <img class="img-fluid lazy" data-original="{% static 'blog/img/noimage.png' %}" alt="{{ post.title }}">
      {% endif %}
    </div><!-- card-bodyの左側終わり -->
  
    <!-- card-bodyの右側 -->
    <div class="col-xs-12 col-sm-6">
      <span class="badge badge-{{ mysite.color }} badge-pill">{% by_the_time post.created_at %}</span>
      <span class="badge badge-{{ mysite.color }} badge-pill">{{ post.created_at }}</span>
      <br>
  
      <span class="badge badge-{{ mysite.color }}">
        <a class="text-white" href="{% url 'blog:category' post.category.name %}">{{ post.category.name }}</a>
      </span>
      <br>
  
      {% for tag in post.tag.all %}
        <span class="badge badge-{{ mysite.color }}">
          <a class="text-white" href="{% url 'blog:tag' tag.name %}">{{ tag.name }}</a>
        </span>
      {% endfor %}
      <hr>
  
      <a class="btn btn-outline-{{ mysite.color }} btn-lg btn-block" href="{% url 'blog:detail' post.pk %}">続きを読む</a>
      <br>
  
      {% if user.is_authenticated %}
        <a href="{% url 'admin:blog_post_change' post.pk %}">管理画面へ</a>
      {% endif %}
    </div><!-- card-bodyの右側おわり -->
  
  </div><!-- card-body終了 -->

</div>

blog/templates/blog/widgets/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-{{ mysite.color }}">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'blog:index' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'blog:tag_list' %}">All Tag</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" target="_blank" href="{% url 'blog:feed' %}" rel="nofollow">Feed</a>
      </li>
      {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:private' %}" rel="nofollow">Private</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" target="_blank" href="{% url 'admin:index' %}" rel="nofollow">Admin</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:ping' %}" rel="nofollow">Ping</a>
        </li>
      {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0" action="{% url 'blog:index' %}">
      {{ global_form.keyword }}
      <button class="btn my-2 my-sm-0" type="submit">検索</button>
    </form>
  </div>
</nav>

blog/templates/blog/widgets/page.html
{% load blogfilter %}
<nav aria-label="Page navigation">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?{% url_replace request 'page' 1 %}" aria-label="Previous">
          &laquo;
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?{% url_replace request 'page' page_obj.previous_page_number %}" aria-label="Previous">
          &lsaquo;
        </a>
      </li>
    {% endif %}

    <li class="page-item disabled"><a class="page-link" href="#!">{{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a></li>

    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?{% url_replace request 'page' page_obj.next_page_number %}" aria-label="Next">
          &rsaquo;
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?{% url_replace request 'page' page_obj.paginator.num_pages %}" aria-label="Next">
          &raquo;
        </a>
      </li>
    {% endif %}
  </ul>
</nav>

blog/templates/blog/widgets/popular_post_list.html
 {% if popular_post_list %}
<!-- 過去の人気記事一覧 -->
<div class="list-group my-5 col-12">
    <a href="#" class="list-group-item text-white bg-{{ mysite.color }}">
      過去1週間の人気記事
    </a>
    {% for popular in popular_post_list %}
    <a class="list-group-item" href="{{ popular.url }}">
        {{ popular.title }} - {{ popular.page_view }}View
    </a>
    {% endfor %}
</div><!-- 過去の人気記事一覧終了 -->
{% endif %}

blog/templates/blog/widgets/side_category.html
<div class="list-group">
  <a href="#" class="list-group-item text-white bg-{{ mysite.color }}">
    All Category
  </a>
  {% for category in categories %}
  <a class="list-group-item" href="{% url 'blog:category' category.name %}">
    {{ category.name }}<span class="badge badge-{{ mysite.color }} badge-pill float-right text-white">{{ category.num_posts }}</span>
  </a>
  {% endfor %}
</div>

blog/templates/blog/widgets/side_comment.html
{% load blogfilter %}

<div class="hidden-sm-down list-group my-5">
  <a href="#" class="list-group-item text-white bg-{{ mysite.color }}">
    Comment
  </a>
  {% for comment in comments  %}
  <a class="list-group-item" href="{% url 'blog:detail' comment.target.pk %}#comment-area" rel="nofollow">
      {{ comment.name }}(返信:{{ comment.num_recomments }})
      <span class="badge badge-{{ mysite.color }} badge-pill float-right text-white">{% by_the_time comment.created_at %}</span>
  </a>
  {% endfor %}    
</div> <!-- コメント一覧終了 -->

blog/templates/blog/widgets/side_link.html
<div class="list-group my-5">
  <a href="#" class="list-group-item text-white bg-{{ mysite.color }}">
    Link
  </a>
  {% for link in links  %}
  <a class="list-group-item" href="{{ link.adrs }}" target="_blank" rel="nofollow">
      {{ link.name }}
  </a>
  {% endfor %}
</div> <!-- リンク一覧終了 -->

blog/templates/blog/widgets/side_tag.html
<div class="list-group mt-5">
  <a href="#" class="list-group-item text-white bg-{{ mysite.color }}">
    Tag
  </a>
  {% for tag in tags  %}
  <a class="list-group-item" href="{% url 'blog:tag' tag.name %}">
      {{ tag.name }}<span class="badge badge-{{ mysite.color }} badge-pill float-right text-white">{{ tag.num_posts }}</span>
  </a>
  {% endfor %}
  <a href="{% url 'blog:tag_list' %}" class="list-group-item">
    >>> 全てのタグを見る
  </a>
</div><!-- タグ一覧終了 -->