blog/urls.py
from django.urls import path
from django.contrib.sitemaps.views import sitemap
from . import views
from .feeds import LatestEntriesFeed
from .sitemap import (
    PostSitemap, TagSitemap,
    CategorySitemap, StaticSitemap
)

app_name = 'blog'

sitemaps = {
    'post': PostSitemap,
    'category': CategorySitemap,
    'tag': TagSitemap,
    'static': StaticSitemap,
}


urlpatterns = [
    path('', views.PostIndexView.as_view(), name='index'),

    path('ping/', views.ping, name='ping'),

    path('alltag/', views.TagListView.as_view(), name='tag_list'),

    path('detail/<int:pk>/', views.PostDetailView.as_view(), name='detail'),

    path('category/<str:category>/', views.CategoryView.as_view(), name='category'),

    path('tag/<str:tag>/', views.TagView.as_view(), name='tag'),

    path('comment/<int:pk>/', views.CommentCreateView.as_view(), name='comment'),
    path('recomment/<int:pk>/', views.ReCommentCreateView.as_view(), name='recomment'),
    path('file_download/<int:pk>/', views.file_download, name='file_download'),


    path('private/', views.PostPrivateIndexView.as_view(), name='private'),

    path('latest/feed/', LatestEntriesFeed(), name='feed'),
    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
]

blog/models.py
import os
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.contrib.sites.models import Site
from django.db import models
from django.utils import timezone


# サイト詳細情報のテーマカラーの選択肢
SITE_COLORS = (
    ('primary', '青色'),
    ('secondary', '灰色'),
    ('success', '緑色'),
    ('info', '水色'),
    ('warning', '黄色'),
    ('danger', '赤'),
    ('dark', '黒'),
)

DEFAULT_HEADER_TEXT = """\
このブログはDjangoとBootstrap4で作成されました
[filter url]https://github.com/naritotzawa/django-torina-blog<split>Githubのソースコード[end]\
"""


class Category(models.Model):
    """カテゴリー"""
    name = models.CharField('カテゴリ名', max_length=255)

    def __str__(self):
        """str."""
        return self.name


class Tag(models.Model):
    """タグ"""
    name = models.CharField('タグ名', max_length=255)

    def __str__(self):
        """str."""
        return self.name


class Post(models.Model):
    """記事"""
    title = models.CharField('タイトル', max_length=255)
    text = models.TextField('本文')
    category = models.ForeignKey(
        Category, verbose_name='カテゴリ', on_delete=models.PROTECT)
    tag = models.ManyToManyField(Tag, blank=True, verbose_name='タグ')
    thumnail = models.ImageField(
        'サムネイル', upload_to='post_thumbnail/%Y/%m/%d/', blank=True, null=True)
    is_publick = models.BooleanField('公開可能か?', default=True)
    friend_posts = models.ManyToManyField(
        'self', verbose_name='関連記事', blank=True)
    description = models.TextField('記事の説明', blank=True)
    files = GenericRelation('File')
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.title

    def get_description(self):
        if self.description:
            return self.description
        else:
            description = 'カテゴリ:{0} タグ:{1}'
            category = self.category
            tags = ' '.join(tag.name for tag in self.tag.all())
            description = description.format(category, tags)
            return description

    def get_next(self):
        """次の記事を取得する(日付)

        パフォーマンス的に、無駄が多い処理ですが、APIとして一応残しておきます。
        """
        next_post = Post.objects.filter(
            is_publick=True, created_at__gt=self.created_at
        ).order_by('-created_at')
        if next_post:
            return next_post.last()
        return None

    def get_prev(self):
        """前の記事を取得する(日付)

        パフォーマンス的に、無駄が多い処理ですが、APIとして一応残しておきます。
        """
        prev_post = Post.objects.filter(
            is_publick=True, created_at__lt=self.created_at
        ).order_by('-created_at')
        if prev_post:
            return prev_post.first()
        return None


class Comment(models.Model):
    """コメント"""
    name = models.CharField('名前', max_length=255, default='名無し')
    text = models.TextField('コメント')
    icon = models.ImageField(
        'サムネイル', upload_to='comment_thumbnail/%Y/%m/%d/', blank=True, null=True)
    target = models.ForeignKey(
        Post, on_delete=models.CASCADE, verbose_name='対象記事')
    files = GenericRelation('File')
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.text[:10]

    def get_filename(self):
        """ファイル名を取得する"""
        return os.path.basename(self.file.url)


class ReComment(models.Model):
    """返信コメント"""
    name = models.CharField('名前', max_length=255, default='名無し')
    text = models.TextField('コメント')
    icon = models.ImageField(
        'サムネイル', upload_to='recomment_thumbnail/%Y/%m/%d//', blank=True, null=True)
    target = models.ForeignKey(
        Comment, on_delete=models.CASCADE, verbose_name='対象コメント')
    files = GenericRelation('File')
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.text[:10]

    def get_filename(self):
        """ファイル名を取得する"""
        return os.path.basename(self.file.url)


class Link(models.Model):
    """リンク"""
    name = models.CharField('リンク名', max_length=255)
    adrs = models.CharField('アドレス', max_length=255)

    def __str__(self):
        return self.name


class Analytics(models.Model):
    """アナリティクスの情報"""
    name = models.CharField('アナリティクス', max_length=255, blank=True)
    html = models.TextField('アナリティクスHTML', blank=True)

    def __str__(self):
        return self.name


class Ads(models.Model):
    """広告関連"""
    name = models.CharField('広告名', max_length=255, blank=True)
    html = models.TextField('広告HTML', blank=True)

    def __str__(self):
        return self.name


class SiteDetail(models.Model):
    """サイトの詳細情報"""
    site = models.OneToOneField(Site, verbose_name='Site', on_delete=models.PROTECT)
    title = models.CharField('タイトル', max_length=255, default='サンプルのタイトル')
    header_text = models.TextField('ヘッダーのテキスト', max_length=255, default=DEFAULT_HEADER_TEXT)
    description = models.TextField('サイトの説明', max_length=255, default='サンプルの説明')
    author = models.CharField('管理者', max_length=255, default='サンプルの管理者')
    author_mail = models.EmailField('管理者アドレス', max_length=255, default='your_mail@gmail.com')
    color = models.CharField('サイトテーマ色', choices=SITE_COLORS, default='primary', max_length=30)

    def __str__(self):
        return self.author


class PopularPost(models.Model):
    """人気記事"""
    title = models.CharField('タイトル', max_length=255)
    url = models.CharField('URL', max_length=255)
    page_view = models.IntegerField('ページビュー数')

    def __str__(self):
        return '{0} - {1} - {2}'.format(
            self.url, self.title, self.page_view)


class Image(models.Model):
    """記事に紐づく画像ファイル"""
    title = models.CharField('タイトル', max_length=255, blank=True)
    post = models.ForeignKey(
        Post, verbose_name='記事', on_delete=models.PROTECT,
    )
    src = models.ImageField('画像', upload_to='images/%Y/%m/%d/', help_text='送信後、一度保存してください。')
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return '間接リンク:[filter imgpk]{0}[end] 直接リンク:[filter img]{1}[end]'.format(self.pk, self.src.url)


class File(models.Model):
    """記事やコメントに紐づく添付ファイル"""
    title = models.CharField('タイトル', max_length=255, blank=True)
    src = models.FileField('添付ファイル', upload_to='files/%Y/%m/%d/')
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return 'モデル:{} pk:{} url:{}'.format(self.content_type, self.object_id, self.src.url)

    def get_filename(self):
        """ファイル名を取得する"""
        return os.path.basename(self.src.url)

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
  <head>

    <meta charset="utf-8">
    <meta name="keywords" content="{% block meta_key %}{% endblock %}">
    <meta name="description" content="{% block meta_des %}{% endblock %}">

    <title>{% block title %}{% endblock %}</title>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% block icon %}<link rel="shortcut icon" href="{% static 'blog/img/favicon.ico' %}">{% endblock %}

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'blog/css/base.css'  %}">

    {% block extracss %}{% endblock %}

  </head>
  <body>
    {% block layout %}{% endblock %}

  <!-- jQuery first, then Tether, then Bootstrap JS. -->
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.lazyload/1.9.1/jquery.lazyload.js"></script>
    <script>
        $(function() {
            $("img.lazy").lazyload({
                threshold:200,
                effect:"fadeIn",
                effect_speed:3000,
            });
        });
    </script>

  <!-- Custom JS -->
  {% block extrajs %}{% endblock %}

  {% block analytics %}
    <!-- アナリティクス -->
      {% for anal in analytics %}
        {{ anal.html | safe }}
      {% endfor %}
    <!-- アナリティクス終わり -->
  {% endblock %}
  
  </body>
</html>

blog/templates/blog/comment_form.html
{% extends "blog/main_layout.html" %}
{% load static %}
{% load blogfilter %}
{% block meta_des %}コメント投稿ページ - {{ mysite.title }}{% endblock %}
{% block title %}コメント投稿ページ - {{ mysite.title }}{% endblock %}

{% block bread%}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'blog:index' %}">記事一覧</a></li>
    <li class="breadcrumb-item"><a href="{% url 'blog:category' post.category.name %}">{{ post.category.name }}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'blog:detail' post.pk %}">{{ post.title }}</a></li>
    <li class="breadcrumb-item">コメント</li>
  </ol>
</nav>
{% endblock %}

{% block content %}
{{ form.non_field_errors }}
<form action="" method="POST" enctype='multipart/form-data'>
  {% for field in form %}
    <div class="form-group">
      {{ field.errors }}
      <label for="{{ field.id_for_label }}">{{ field.label }}</label>
      {{ field }}
    </div>
  {% endfor %}<!-- コメント部分のフォーム終わり -->

  {{ formset.management_form }}
  {% for form in formset %}
    {{ form.id }}
    {{ form.non_field_errors }}
    {% for field in form.visible_fields %}
      <div class="form-group">
        {{ field.errors }}
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {{ field }}
      </div>
    {% endfor %}<!-- 1つのファイルフォーム終わり -->

  {% endfor %}<!-- formset終了 -->
  {% csrf_token %}
  <button class="btn btn-{{ mysite.color }}" type="submit">コメントする</button>
  <a class="btn btn-{{ mysite.color }}" href="{% url 'blog:detail' post.pk %}" rel="nofollow">戻る</a>
</form>

{% endblock %}

blog/templates/blog/layout.html
{% extends 'blog/base.html' %}
{% block layout %}

<!-- グローバルナビゲーション -->
{% include 'blog/widgets/nav.html' %}

<!-- ヘッダー -->
{% include 'blog/widgets/header.html' %}

<!-- メインコンテンツ -->
{% block main %}
{% endblock %}

<!-- フッター -->
{% include 'blog/widgets/footer.html' %}

{% endblock %}

blog/templates/blog/main_layout.html
{% extends 'blog/layout.html' %}

{% block main %}
<div class="container">
   {% block bread %}{% endblock %}
  <div class="row">
    <!-- 左側のメインコンテンツ -->
    <main class="col-12 col-md-8">
      {% block content %}
      {% endblock %}
    </main><!-- メインコンテンツ終了 -->

    <!-- 右側のサイドバー -->
    <aside class="col-12 col-md-3 offset-md-1">
      <!-- カテゴリ一覧 -->
      {% include 'blog/widgets/side_category.html' %}

      <!-- タグ一覧 -->
      {% include 'blog/widgets/side_tag.html' %}

      <!-- リンク一覧 -->
      {% include 'blog/widgets/side_link.html' %}

       <!-- コメント一覧 -->
       {% include 'blog/widgets/side_comment.html' %}

      <!-- 広告一覧 -->  
      {% for ad in ads %}
        {{ ad.html | safe }}
      {% endfor %}<!-- 広告一覧終了 -->
    </aside><!-- /サイドバー終了 -->
  </div><!-- /.row -->

  <!-- 人気記事一覧 -->
  <aside>
    {% include 'blog/widgets/popular_post_list.html' %}
  </aside>
</div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends "blog/main_layout.html" %}
{% load static %}

{% block meta_des %}
  {{ post.get_description }}
{% endblock %}

{% block title %}{{post.title}} - {{ mysite.title }}{% endblock %}

{% block bread%}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'blog:index' %}">記事一覧</a></li>
    <li class="breadcrumb-item"><a href="{% url 'blog:category' post.category.name %}">{{ post.category.name }}</a></li>
    <li class="breadcrumb-item">{{ post.title }}</li>
  </ol>
</nav>
{% endblock %}

{% block content %}
<!-- 目次部分 -->
<div id="toc"></div>

<!-- 記事詳細部分 -->
<article>
  {% include 'blog/widgets/detail_card.html' %}
</article>

<!-- コメント一覧 -->
<div id="comment-area">
  {% for comment in post.comment_set.all %}
    {% include 'blog/widgets/detail_comment.html' %}
  {% endfor %}
</div>

<div class="text-center my-5">
  <a class="btn btn-{{ mysite.color }} btn-lg text-white" href="{% url 'blog:comment' post.pk %}" rel="nofollow">コメントページへ</a>
</div>

{% endblock %}

{% block extrajs %}
<script src="{% static 'blog/js/toc.js' %}"></script>
{% endblock %}

blog/templates/blog/post_list.html
{% extends "blog/main_layout.html" %}

{% block meta_des %}
    {% if tag %}
      {{ mysite.title }}の、タグ: {{ tag.name }} の検索結果一覧です。
    {% elif category %}
      {{ mysite.title }}の、カテゴリー: {{ category.name }} の検索結果一覧です。
    {% else %}
        {{ mysite.description }}
    {% endif %}
{% endblock %}

{% block title %}
    {% if tag %}
        {{ tag.name }} | {{ mysite.title }}
    {% elif category %}
        {{ category.name }} | {{ mysite.title }}
    {% else %}
        {{ mysite.title }}
    {% endif %}
{% endblock %}

{% block bread %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'blog:index' %}">記事一覧</a></li>
    {% if tag %}
        <li class="breadcrumb-item">{{ tag.name }}</li>
    {% elif category %}
        <li class="breadcrumb-item">{{ category.name }}</li>
    {% endif %}
  </ol>
</nav>
{% endblock %}

{% block content %}
  {% for post in post_list %}
    <article>
      {% include 'blog/widgets/list_card.html' %}
    </article>
  {% endfor %}
  {% include "blog/widgets/page.html" %}
{% endblock %}

blog/templates/blog/tag_list.html
{% extends "blog/main_layout.html" %}
{% load static %}
{% load blogfilter %}
{% block meta_des %}{{ mysite.title }}のタグ一覧ページです。{% endblock %}
{% block title %}タグ一覧 | {{ mysite.title }}{% endblock %}

{% block bread%}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'blog:index' %}">記事一覧</a></li>
    <li class="breadcrumb-item">タグ一覧</li>
  </ol>
</nav>
{% endblock %}

{% block content %}
  {% for tag in tag_list %}
    <p><a href="{% url 'blog:tag' tag.name %}">{{ tag.name }}({{ tag.num_posts }})</a></p>
    <hr>
  {% endfor %}
{% endblock %}